// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class', // Enable dark mode based on the 'dark' class
  theme: {
    extend: {
      colors: {
        'primary-color': 'var(--color-text-primary)',
        'secondary-color': 'var(--color-text-secondary)',
        'section-bg': 'var(--color-section-bg)',
        'border-color': 'var(--color-border)',
        'card-bg': 'var(--color-card-bg)',
        'card-border': 'var(--color-card-border)',
        'card-text': 'var(--color-card-text)',
        'dropdown-bg': 'var(--color-dropdown-bg)',
        'dropdown-border': 'var(--color-dropdown-border)',
        'dropdown-text': 'var(--color-dropdown-text)',
        'dropdown-hover-bg': 'var(--color-dropdown-hover-bg)',
        'button-primary-text': 'var(--color-button-primary-text)',
        'podcast-icon-light': 'var(--color-podcast-icon-light)',
        'podcast-icon-dark': 'var(--color-podcast-icon-dark)',
        'footer-text': 'var(--color-footer-text)',
        'logo-text': 'var(--color-logo-text)',
        'layer-outer-bg': 'var(--color-layer-outer-bg)',
        'layer-inner-bg': 'var(--color-layer-inner-bg)',
        'welcome-section-bg': 'var(--color-welcome-section-bg)',
        'onboarding-card-bg': 'var(--color-onboarding-card-bg)',
        'tab-nav-bg': 'var(--color-tab-nav-bg)',
        'generated-content-bg': 'var(--color-generated-content-bg)',
        'layer-outer-border': 'var(--color-layer-outer-border)',
        'layer-inner-border': 'var(--color-layer-inner-border)',
        'welcome-section-border': 'var(--color-welcome-section-border)',
        'onboarding-card-border': 'var(--color-onboarding-card-border)',
        'tab-nav-border': 'var(--color-tab-nav-border)',
        'generated-content-border': 'var(--color-generated-content-border)',
        'section-header-border': 'var(--color-section-header-border)',
        'tab-active-underline': 'var(--color-tab-active-underline)',
        'tab-inactive-hover-text': 'var(--color-tab-inactive-hover-text)',
        'content-card-shadow': 'var(--color-content-card-shadow)',
        'content-card-bg': 'var(--color-content-card-bg)',
        'panel-bg': 'var(--color-panel-bg)',
        'panel-border': 'var(--color-panel-border)',
        'button-secondary-bg': 'var(--color-button-secondary-bg)',
        'button-secondary-text': 'var(--color-button-secondary-text)',
        'button-secondary-hover-bg': 'var(--color-button-secondary-hover-bg)',
        'button-secondary-hover-text': 'var(--color-button-secondary-hover-text)',
        'input-bg': 'var(--color-input-bg)',
        'input-border': 'var(--color-input-border)',
        'input-focus-ring': 'var(--color-input-focus-ring)',
        'input-text': 'var(--color-input-text)',
        'input-box-bg': 'var(--color-input-box-bg)',
        'input-box-border': 'var(--color-input-box-border)',
        'chat-header-text': 'var(--color-chat-header-text)',
        'chat-input-panel-bg': 'var(--color-chat-input-panel-bg)',
        'chat-input-field-bg': 'var(--color-chat-input-field-bg)',
        'icon-primary': 'var(--color-icon-primary)',
        'send-button-bg': 'var(--color-send-button-bg)',
        'user-bubble-icon-bg-solid': 'var(--color-user-bubble-icon-bg-solid)',
        'chat-bubble-user-bg': 'var(--color-chat-bubble-user-bg)',
        'chat-bubble-ai-bg': 'var(--color-chat-bubble-ai-bg)',
        'message-bg': 'var(--color-message-bg)',
        'message-text': 'var(--color-message-text)',
        'message-border': 'var(--color-message-border)',
        'suggestion-tag-bg': 'var(--color-suggestion-tag-bg)',
        'suggestion-tag-text': 'var(--color-suggestion-tag-text)',
        'suggestion-tag-border': 'var(--color-suggestion-tag-border)',
        'suggestion-tag-hover-bg': 'var(--color-suggestion-tag-hover-bg)',
        'icon': 'var(--color-icon)',
        'checkbox-checked-bg': 'var(--color-checkbox-checked-bg)',
        'checkbox-bg': 'var(--color-checkbox-bg)',
        'checkbox-border': 'var(--color-checkbox-border)',
        'modal-bg': 'var(--color-modal-bg)',
        'modal-text': 'var(--color-modal-text)',
        'modal-border': 'var(--color-modal-border)',
        'modal-button-bg': 'var(--color-modal-button-bg)',
        'modal-button-hover-bg': 'var(--color-modal-button-hover-bg)',
        'modal-button-text': 'var(--color-modal-button-text)',
        'modal-close-button-hover': 'var(--color-modal-close-button-hover)',
        'modal-info-text': 'var(--color-modal-info-text)',
        'browser-frame-bg': 'var(--color-layer-outer-bg)',
        'browser-title-address-bar-bg': 'var(--color-tab-nav-bg)',
        'browser-address-input-bg': 'var(--color-input-bg)',
        'browser-address-text-primary': 'var(--color-text-primary)',
        'browser-address-text-secondary': 'var(--color-text-secondary)',
        'browser-content-bg': 'var(--color-generated-content-bg)',
        'welcome-section-bg': 'var(--color-welcome-section-bg)',
        'onboarding-card-border': 'var(--color-onboarding-card-border)',
        'tab-nav-border': 'var(--color-tab-nav-border)',
        'tab-nav-bg': 'var(--color-tab-nav-bg)',
      },
      backgroundImage: {
        'gradient-bg': 'linear-gradient(to bottom right, var(--gradient-bg-from), var(--gradient-bg-to))',
        'feature-icon-bg-gradient': 'linear-gradient(to right, var(--color-feature-icon-bg-from), var(--color-feature-icon-bg-to))',
        'button-primary-gradient': 'linear-gradient(to right, var(--gradient-button-primary-from), var(--gradient-button-primary-to))',
        'button-primary-gradient-hover': 'linear-gradient(to right, var(--gradient-button-primary-hover-from), var(--gradient-button-primary-hover-to))',
        'chat-gradient-highlight': 'linear-gradient(to right, var(--gradient-highlight-from), var(--gradient-highlight-to))',
        'user-bubble-icon-bg-gradient': 'linear-gradient(to right, var(--gradient-user-bubble-icon-from), var(--gradient-user-bubble-icon-to))',
        'ai-bubble-icon-bg-gradient': 'linear-gradient(to right, var(--gradient-ai-bubble-icon-from), var(--gradient-ai-bubble-icon-to))',
        'chat-header-gradient': 'linear-gradient(to right, var(--gradient-chat-header-from), var(--gradient-chat-header-to))',
        'svg-bg-gradient': 'linear-gradient(135deg, var(--gradient-svg-bg-from), var(--gradient-svg-bg-to))',
      },
      keyframes: {
        'voiceWaveFlow': {
          '0%': { strokeDashoffset: '0', strokeWidth: '3', opacity: '0.7' },
          '50%': { strokeDashoffset: '200', strokeWidth: '4', opacity: '1' },
          '100%': { strokeDashoffset: '400', strokeWidth: '3', opacity: '0.7' },
        },
        'gentleShake': {
          '0%': { transform: 'translate(0px, 0px)' },
          '25%': { transform: 'translate(0.5px, -0.5px)' },
          '50%': { transform: 'translate(-0.5px, 0.5px)' },
          '75%': { transform: 'translate(0.5px, 0.5px)' },
          '100%': { transform: 'translate(0px, 0px)' },
        },
        'micPulseEffect': {
          '0%': { transform: 'translate(0, 0) scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'translate(0, -2px) scale(1.01)', filter: 'brightness(1.05)' },
          '100%': { transform: 'translate(0, 0) scale(1)', filter: 'brightness(1)' },
        },
        'iconMotion': {
          '0%': { transform: 'translate(0px, 0px) scale(0.9) rotate(0deg)', opacity: '0.8' },
          '25%': { transform: 'translate(10px, -15px) scale(1) rotate(8deg)', opacity: '0.9' },
          '50%': { transform: 'translate(-15px, 10px) scale(0.95) rotate(-5deg)', opacity: '0.85' },
          '75%': { transform: 'translate(5px, 20px) scale(1.05) rotate(10deg)', opacity: '0.95' },
          '100%': { transform: 'translate(0px, 0px) scale(0.9) rotate(0deg)', opacity: '0.8' },
        },
        'cellularWavePulse': {
          '0%': { opacity: '0.2' },
          '50%': { opacity: '0.8' },
          '100%': { opacity: '0.2' },
        },
      },
      animation: {
        'voice-wave': 'voiceWaveFlow 4s linear infinite',
        'gentle-shake': 'gentleShake 4s ease-in-out infinite, micPulseEffect 3s ease-in-out infinite',
        'social-icon-motion': 'iconMotion 15s ease-in-out infinite',
        'cellular-wave-pulse': 'cellularWavePulse 3s ease-in-out infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}